
## 1. Installing packages: `RCurl`, `stringr`, `rvest`

Inside the R prompt, run the following command

```{r}
package_list <- c('RCurl','stringr','rvest')
install.packages(package_list)
```

You can test that all packages are installed and usable by load them all and check session information to see the loaded packages under header *other attached packages*


```{r}
library(RCurl)
library(stringr)
library(rvest)
sessionInfo()
```

## 2. Download PhantomJS:

```{r}
if (!file.exists(file.path('bin'))){
    dir.create(file.path('bin'))
    print ('Create bin directory')
} else {
    print ("Directory already exists")
}

if (Sys.info()['sysname'] == 'Windows'){
  download.file('https://drive.google.com/a/g.clemson.edu/uc?authuser=1&id=0B1cRCY8U8bTcM2ZsSS1CclROOGc&export=download',
                file.path('bin','phantomjs.exe'),
                mode='wb')
} else if (Sys.info()['sysname'] == 'Linux'){
  download.file('https://drive.google.com/a/g.clemson.edu/uc?export=download&confirm=2CrO&id=0B1cRCY8U8bTcLVFpdVRWLUk4eGM',
                file.path('bin','phantomjs'),
                mode='wb')
} else { # probably MacOSX
  download.file('https://drive.google.com/a/g.clemson.edu/uc?authuser=1&id=0B1cRCY8U8bTcQS1sZElJZE1VOVE&export=download',
                file.path('bin','phantomjs'),
                mode='wb')
}

```